# Generated by Django 4.2 on 2023-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Saldo'),
        ),
    ]
