# Generated by Django 4.2 on 2023-04-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOtroRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(default='', max_length=300, verbose_name='Nombre')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tiporubro', models.IntegerField(choices=[(1, 'SERVICIO'), (2, 'BIEN'), (3, 'RENTA INVERSIONES')], default=1, verbose_name='Tipo de Rubro')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'verbose_name': 'Tipo otro rubro',
                'verbose_name_plural': 'Tipo otros rubros',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fin', models.DateField(verbose_name='Fecha fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'verbose_name': 'Periodo de cursos',
                'verbose_name_plural': 'Periodos de cursos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'CREADO'), (2, 'APERTURADO'), (3, 'CERRADO'), (4, 'CANCELADO')], null=True, verbose_name='Estado Curso')),
                ('horasvirtual', models.IntegerField(default=0, verbose_name='Horas Virtuales')),
                ('minasistencia', models.IntegerField(default=0, verbose_name='Asistencia mínima para aprobar')),
                ('minnota', models.IntegerField(default=0, verbose_name='Nota mínima para aprobar')),
                ('cupo', models.IntegerField(default=0, verbose_name='Cupo')),
                ('cuotas', models.IntegerField(default=0, verbose_name='Cuotas')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Costo del curso')),
                ('gcuotas', models.BooleanField(default=False, verbose_name='El curso genera cuotas?')),
                ('inscripcion', models.BooleanField(default=False, verbose_name='El curso aplica inscripción?')),
                ('oferta', models.BooleanField(default=False, verbose_name='Aplica oferta?')),
                ('costooferta', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Costo del curso aplicando oferta')),
                ('matricula', models.BooleanField(default=False, verbose_name='Matrícula')),
                ('costomatricula', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Costo de la matrícula')),
                ('modalidad', models.IntegerField(blank=True, choices=[(1, 'VIRTUAL'), (2, 'PRESENCIAL')], null=True, verbose_name='Modalidad DEL CURSO')),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('fechainicioinscripcion', models.DateField(blank=True, null=True)),
                ('fechafininscripcion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observacion')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('visualizar', models.BooleanField(default=False, verbose_name='Visualizar')),
                ('publicarcurso', models.BooleanField(default=False, verbose_name='Publicar')),
                ('planificacion', models.ImageField(blank=True, null=True, upload_to='planificacioncurso', verbose_name='Planificación')),
                ('finalizarcurso', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Curso terminado?')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.docente', verbose_name='Docente')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administrativo.periodo', verbose_name='Periodo')),
                ('tiporubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administrativo.tipootrorubro', verbose_name='Rubro para cuota')),
                ('tiporubroinscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administrativo.tipootrorubro', verbose_name='Rubro para inscripcion')),
                ('tiporubromatricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administrativo.tipootrorubro', verbose_name='Rubro para matricula')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
