# Generated by Django 4.2 on 2023-04-21 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativo', '0002_tipootrorubro_periodo_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEvaluativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('notamaxima', models.FloatField(default=0, verbose_name='Nota maxima')),
                ('notaaprobar', models.FloatField(default=0, verbose_name='Nota para aprobar')),
                ('asistenciaaprobar', models.FloatField(default=0, verbose_name='Asistencia para aprobar')),
                ('observaciones', models.TextField(default='', max_length=200, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'verbose_name': 'Modelo evaluativo',
                'verbose_name_plural': 'Modelos evaluativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleModeloEvaluativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(default='', max_length=10, verbose_name='Nombre campo')),
                ('notaminima', models.FloatField(default=0, verbose_name='Nota minima')),
                ('notamaxima', models.FloatField(default=0, verbose_name='Nota maxima')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden en acta')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.modeloevaluativo', verbose_name='Modelo')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'verbose_name': 'Detalle del modelo evaluativo',
                'verbose_name_plural': 'Detalles de los modelos evaluativos',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='modeloevaluativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administrativo.modeloevaluativo', verbose_name='Modelo Evaluativo'),
        ),
    ]
