# Generated by Django 4.2 on 2023-04-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_periodo_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='costoinscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Costo de la inscripción'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fondo',
            field=models.ImageField(blank=True, null=True, upload_to='fondocursos', verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='planificacion',
            field=models.FileField(blank=True, null=True, upload_to='planificacioncurso', verbose_name='Planificación'),
        ),
    ]
