# Generated by Django 4.2 on 2023-04-21 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativo', '0006_remove_curso_fondo_curso_fondocursos_curso_fondoweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotasCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('numerocuota', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de la cuota')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor de la cuota')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administrativo.curso', verbose_name='Curso')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
