# Generated by Django 4.2 on 2023-04-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0007_cuotascurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='cuota',
            field=models.IntegerField(default=0, verbose_name='Cuota'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.curso'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='fechavencimiento',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='tipocuota',
            field=models.IntegerField(choices=[(1, 'INSCRIPCION'), (2, 'MATRICULA'), (3, 'CUOTA'), (4, 'CANTIDAD')], default=3),
        ),
        migrations.AddField(
            model_name='rubro',
            name='tiporubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.tipootrorubro'),
        ),
        migrations.AddField(
            model_name='tipootrorubro',
            name='descripcion',
            field=models.CharField(default='', max_length=800, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cancelado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
