# Generated by Django 4.2 on 2023-04-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_rubro_cuota_rubro_curso_rubro_fechavencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tiporubrocuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administrativo.tipootrorubro', verbose_name='Rubro para cuotas'),
        ),
    ]
