# Generated by Django 4.2 on 2023-04-22 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativo', '0009_curso_tiporubrocuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscritoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'APROBADO'), (2, 'REPROBADO')], default=2, null=True, verbose_name='Modalidad DEL CURSO')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.alumno', verbose_name='Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.curso', verbose_name='Curso')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'verbose_name': 'Inscrito Curso',
                'verbose_name_plural': 'Inscritos por curso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotaInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('notafinal', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Nota final')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.inscritocurso', verbose_name='Alumno')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.detallemodeloevaluativo', verbose_name='Modelo Evaluativo: N1, N2, N3, etc.')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
            ],
            options={
                'verbose_name': 'Nota del inscrito',
                'verbose_name_plural': 'Notas del inscrito',
                'ordering': ['id'],
            },
        ),
    ]
