# Generated by Django 4.2 on 2023-04-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0011_caja_sesioncaja_valorrecaudado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['id'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='sesioncaja',
            options={'ordering': ['id'], 'verbose_name': 'Sesion Caja', 'verbose_name_plural': 'Sesiones de caja'},
        ),
        migrations.AlterModelOptions(
            name='valorrecaudado',
            options={'ordering': ['id'], 'verbose_name': 'Valor recaudado en la sesión de caja', 'verbose_name_plural': 'Valores recaudados en las sesiones de caja'},
        ),
    ]
