# Generated by Django 4.2 on 2023-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0012_alter_caja_options_alter_sesioncaja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='valorinicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor con el que comienza la caja'),
        ),
    ]
