# Generated by Django 4.2 on 2023-04-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0013_sesioncaja_valorinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='sesioncaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.sesioncaja'),
        ),
    ]
