# Generated by Django 4.2 on 2023-04-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_cierresesioncaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubro',
            name='alumno',
        ),
        migrations.AddField(
            model_name='rubro',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.persona'),
        ),
    ]
