# Generated by Django 4.2 on 2023-04-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0017_cargo_delete_cargodocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.cargo'),
        ),
    ]
