# Generated by Django 4.2 on 2023-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0018_docente_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.IntegerField(blank=True, choices=[(1, 'VIRTUAL'), (2, 'PRESENCIAL')], default=1, null=True, verbose_name='Modalidad DEL CURSO'),
        ),
    ]
